〇予想と回答


  予想
  図解はmdファイルに記載
  
・f3
  // 回答:
  // 0秒後に A が出力され、その後にエラー処理が実行され、Bが出力される。その後にCが出力される。
  //
  // 説明:
  // wait0の解決後に logA が実行され、wait2().then(errX) の解決後 (B 出力),その後 finallyが実行されlogCが実行されるため。

  回答
PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
C
A
file:///C:/Users/sumi6/javascript/github/sample/exercises/ch13/ex02/index.js:34
  throw new Error("X");
        ^

Error: X
    at errX (file:///C:/Users/sumi6/javascript/github/sample/exercises/ch13/ex02/index.js:34:9)

Node.js v22.14.0
最初にCが出力され、ほぼ同時にAが出力された。Bは出力されずエラーメッセージが表示された。

・f4
  // 回答:
  // 2秒後に A が出力され、return 40で40を返す。その後に1秒後に、Bが出力され、return100で100を返す。その後に変数vの値が表示される。
  //
  // 説明:
  // wait2の解決後に logA が実行され、wait(1000)の解決後 (B 出力),その後vの値100が出力される。

回答
  PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
A
B
100

予想通りの結果に見える。

・f5
  // 回答:
  // 2秒後に A が出力され、return 40で40を返す。その後に1秒後に、Bが出力され、return100で100を返す。その後に変数vの値が表示される。
  //
  // 説明:
  // wait2の解決後に logA が実行され、wait1()の解決後 (B 出力),その後vの値100が出力される。

回答
PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
B
A
40

2つ目の引数が関数ではなくPromiseになっているため、Bが最初に表示された？その後Aが表示され、
vの値が表示されたvは40。Bの処理が先に実施されてv=100がその後のAの処理で40へ上書きされた？

・f6
  // 回答:
  // 1秒後に A が出力され、その後に1秒後に、Bが出力され、Aが表示されてから2秒後にＣが表示される。
  //
  // 説明:
  // wait1の解決後に logA が実行され、同時にBとCのwait1,wait2が同時に実行される。

回答
PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
A
B
C

Aが表示後1秒後にBが表示され、その1秒後にCが表示された。
予想と同じ結果と考える。

・f7
  // 回答:
  // 1秒後に A が出力され、その後に1秒後に、Bが出力され、Aが表示されてから2秒後にＣが表示される。
  //
  // 説明:
  // wait1の解決後に logA が実行され、同時にBとCのwait1,wait2が同時に実行される。

回答
PS C:\Users\sumi6\javascript\github\sample\exercises\ch13\ex02> node index.js
A
B
C

Aが表示後1秒後にBが表示され、その1秒後にCが表示された。
予想と同じ結果と考える。
